name: Linter and tests
on:
  push:
    branches-ignore:
      - master
    paths:
      - '**.ts'
      - '**.sol'
      - '**.yml'
jobs:
  start:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Determine npm cache directory
        id: npm-cache
        run: echo "::set-output name=dir::$(npm config get cache)"

      - name: Restore npm cache
        uses: actions/cache@v2
        with:
          path: ${{ steps.npm-cache.outputs.dir }}
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Install dependencies
        run: npm i
        env:
          CI: false

      - name: Run bootstrap
        run: npm run bootstrap -- --no-ci

      - name: Run link
        run: npm run link

      - name: Run compile
        run: npm run compile

      - name: Run linter
        run: npm run linter

      - name: Run tests
        env:
          REPORT_GAS: 1
        run: npm run test